
project_id = "lzwkccarbwokfxrzffjd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://preview--twyne-ai.lovable.app"
additional_redirect_urls = [
  "https://preview--twyne-ai.lovable.app/auth/callback",
  "https://preview--twyne-ai.lovable.app/auth/callback/spotify",
  "https://preview--twyne-ai.lovable.app/auth/callback/youtube"
]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.spotify-auth-url]
verify_jwt = false

[functions.google-auth-url]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = true

[functions.google-auth]
verify_jwt = true
